model_args:
  num_classes: 1116
  c2d_type: resnet18
  conv_type: 2
  use_bn: True
  hidden_size: 1024
  # SMKD
  weight_norm: True # False
  share_classifier: True # False

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [20, 35]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False
  loss_weights:
    SeqCTC: 1.0
    # VAC
    ConvCTC: 1.0
    # Dist: 10.0

trainer_args:
  accelerator: "gpu"
  devices: 2
  max_epochs: 40
  ckpt_dir: output/SLR/lightning_ckpt

evaluate_args:
  eval_script_dir: src/SLR/models/evaluation
  eval_output_dir: output/SLR/eval_result/
  eval_label_dir: data/SLR/processed/phoenix2014-T

dataset_args:
  info_dir: data/SLR/processed/phoenix2014-T
  img_dir: data/SLR/processed/phoenix2014-T/PHOENIX-2014-T/features/fullFrame-256x256px
  batch_size: 1
  num_worker: 10
