# phase: train
# dataset: phoenix14-T
# # dataset: phoenix14-si5
# num_epoch: 40
# work_dir: ./output/SLR/T_sota/
# batch_size: 2
# random_seed: 0
# test_batch_size: 2
# num_worker: 10
# device: 0,1
# log_interval: 50
# eval_interval: 1
# save_interval: 5
# evaluate_tool: python # sclite

dataset_args:
  info_dir: "./data/SLR/processed/phoenix2014"
  img_dir: "./data/SLR/processed/phoenix2014/phoenix-2014-multisigner/features/fullFrame-256x256px"
  batch_size: 2
  num_worker: 10

model_args:
  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: True
  hidden_size: 1024
  # SMKD
  weight_norm: True # False
  share_classifier: True # False

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [20, 35]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False
  loss_weights:
    SeqCTC: 1.0
    # VAC
    ConvCTC: 1.0
    # Dist: 10.0

trainer_args:
  accelerator: "gpu"
  devices: 1
  max_epochs: 40
