model_args:
  num_classes: 1296
  c2d_type: resnet18
  c2d_weights_name: ResNet18_Weights.IMAGENET1K_V1
  conv_type: 2
  use_bn: True
  hidden_size: 1024
  # SMKD
  weight_norm: True # False
  share_classifier: True # False

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [20, 35]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False
  loss_weights:
    SeqCTC: 1.0
    # VAC
    ConvCTC: 1.0
    # Dist: 10.0

trainer_args:
  accelerator: "gpu"
  devices: 1
  max_epochs: 40
  ckpt_dir: output/SLR/lightning_ckpt

evaluate_args:
  eval_script_dir: src/SLR/models/evaluation
  eval_output_dir: output/SLR/eval_result/
  eval_label_dir: data/SLR/processed/phoenix2014

dataset_args:
  info_dir: data/SLR/processed/phoenix2014
  img_dir: data/SLR/processed/phoenix2014/phoenix-2014-multisigner/features/fullFrame-256x256px
  batch_size: 2
  num_worker: 10
