model_args:
  num_classes: 1116
  c2d_type: resnet18
  conv_type: 2
  use_bn: True
  hidden_size: 1024
  # SMKD
  weight_norm: True
  share_classifier: True

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [20, 35]
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False
  loss_weights:
    SeqCTC: 1.0
    # VAC
    ConvCTC: 1.0
    # Dist: 10.0

trainer_args:
  accelerator: "gpu"
  devices: 2
  max_epochs: 40
  precision: 16 # 32 or 16
  ckpt_dir: output/SLR/Phoenix2014T/ckpt

evaluate_args:
  eval_script_dir: src/SLR/models/evaluation
  eval_output_dir: output/SLR/Phoenix2014T/eval_result

dataset_args:
  dataset_name: Phoenix2014T
  img_size: [256, 256]
  raw_info_dir: data/SLR/raw/Phoenix2014T/annotations/manual
  raw_img_dir: data/SLR/raw/Phoenix2014T/features/fullFrame-210x260px
  processed_info_dir: data/SLR/processed/Phoenix2014T
  processed_img_dir: data/SLR/processed/Phoenix2014T/features/fullFrame-256x256px
  batch_size: 1
  num_worker: 8
