dataset_root: ./data/SLR/processed/phoenix2014-T/PHOENIX-2014-T
dict_path: ./data/SLR/processed/phoenix2014-T/gloss_dict.npy
evaluation_dir: ./src/SLR/models/evaluation
evaluation_prefix: groundtruth
label_dir: ./data/SLR/processed/phoenix2014-T
